name: Publish package
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - run: |
          git config --global user.name "Erik Tasi"
          git config --global user.email "tasi.erik15@gmail.com"
          npm version patch -m "[skip ci] Increase version"
      - run: |
          npm i
          npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: git push